#!/usr/bin/env python3
import nltk
import os
import sys
import helpers
from analyzer import Analyzer
from termcolor import colored


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet @screen_name")
    #get user screen name
    screen_name = sys.argv[1].lstrip("@")
    if helpers.get_user_timeline(screen_name)==None:
        sys.exit("user protected or doesn't exist")
    #tokenize tweet
    tweets = helpers.get_user_timeline(screen_name)
    tokenizer = nltk.tokenize.TweetTokenizer()
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # analyze tweet
    
    analyzer = Analyzer(positives, negatives)
    for tweet in tweets:
        score = 0
        tokens = tokenizer.tokenize(tweet)
        for token in tokens:
            score = score+analyzer.analyze(token)
        text = str(score)+" "+tweet
        if score > 0.0:
            print(colored(text, "green"))
        elif score < 0.0:
            print(colored(text, "red"))
        else:
            print(colored(text, "yellow")) 
        
        
if __name__ == "__main__":
    main()